### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by kornelremete** [amaximus/met_alerts_hu#20]
I have the following error message:

Logger: homeassistant.components.sensor
Source: custom_components/met_alerts_hu/sensor.py:113
Integration: Sensor (documentation, issues)
First occurred: 11:39:26 (1 occurrences)
Last logged: 11:39:26

met_alerts_hu: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/met_alerts_hu/sensor.py", line 182, in async_update
    mdata = await async_get_mdata(self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/met_alerts_hu/sensor.py", line 113, in async_get_mdata
    ff_json += "{\"level\":\"" + a_lvl + \
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Sygnus83** [comment]
Me too!

**Comment by amaximus** [comment]
Newer version 2.6.0 fixes the issue, adds support for the new alert condition.

Please update the integration and get back to me with results.

**Comment by Sygnus83** [comment]
> Newer version 2.6.0 fixes the issue, adds support for the new alert condition.
> 
> Please update the integration and get back to me with results.

Working good ! Thanks for the fast update !

**Comment by kornelremete** [comment]
Works perfect again.
